# Generated by Django 3.1.1 on 2020-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_auto_20200916_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wins',
            old_name='wins',
            new_name='name',
        ),
    ]
