# Generated by Django 3.1.1 on 2020-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_auto_20200916_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wins',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
