# Generated by Django 3.1.1 on 2020-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_auto_20200916_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
